export const ANALYTICS_CONFIG = {
  CACHE_TTL: 10 * 60 * 1000, // 10 minutes
  POSITIVE_EMOTIONS: new Set(['happy', 'calm', 'focused', 'proud', 'content']),
  INSIGHTS: {
    MIN_SESSIONS_FOR_FULL_ANALYTICS: 5,
    HIGH_CONFIDENCE_PATTERN_THRESHOLD: 0.6,
    MAX_PATTERNS_TO_SHOW: 2,
    MAX_CORRELATIONS_TO_SHOW: 2,
    MAX_PREDICTIONS_TO_SHOW: 2,
    RECENT_EMOTION_COUNT: 7,
    POSITIVE_EMOTION_TREND_THRESHOLD: 0.6,
    NEGATIVE_EMOTION_TREND_THRESHOLD: 0.3,
  },
  CONFIDENCE: {
    THRESHOLDS: {
      EMOTION_ENTRIES: 10,
      SENSORY_ENTRIES: 10,
      TRACKING_ENTRIES: 5,
      DAYS_SINCE_LAST_ENTRY: 7,
    },
    WEIGHTS: {
      EMOTION: 0.3,
      SENSORY: 0.3,
      TRACKING: 0.4,
      RECENCY_BOOST: 0.1,
    },
  },
  HEALTH_SCORE: {
    WEIGHTS: {
      PATTERNS: 20,
      CORRELATIONS: 20,
      PREDICTIONS: 20,
      ANOMALIES: 20,
      MINIMUM_DATA: 20,
    },
  },
  ANALYTICS: {
    MIN_TRACKING_FOR_CORRELATION: 3,
    MIN_TRACKING_FOR_ENHANCED: 2,
    ANALYSIS_PERIOD_DAYS: 30,
  },
};

export type AnalyticsConfig = typeof ANALYTICS_CONFIG;